name: Create Release on Push

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create temporary directory
        run: New-Item -ItemType Directory -Path temp -Force  # Create a temporary directory

      - name: Copy files to temporary directory
        run: |
          # Copy all files except the excluded ones to the temporary directory
          Copy-Item -Path * -Destination temp -Recurse -Force -Exclude ".github", ".gitattributes", "releases/*"

      - name: Zip contents
        run: |
          # Create a zip file from the temporary directory
          Compress-Archive -Path temp\* -DestinationPath releases\gozarcraft-resourcepack-base.zip -CompressionLevel Optimal -Force

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}  # Use the run number as the tag
          name: Release v1.0.${{ github.run_number }}  # Name of the release
          body: |
            This release includes the latest changes.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}  # Use the same tag as the release
          files: releases/gozarcraft-resourcepack-base.zip  # Path to the zip file in the releases directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}